version: "3"

tasks:
    generate:
        desc: "Generate protobuf files"
        cmds:
          - protoc -I proto proto/auth.proto --go_out=./internal/proto/auth --go_opt=paths=source_relative --go_grpc_out=./internal/proto/auth --go_grpc_opt=paths=source_relative
    run:local:
        desc: "Run the server in local environment"
        cmds:
          - go run cmd/sso/main.go --config="./config/local.yml"
    migrator:local:
        desc: "Run database migrations in local environment"
        cmds:
          - go run cmd/migrator/main.go --storage-path="./storage/sso.db" --migrations-path="./migrations"
    migrator:test:
        desc: "Run database migrations for test environment"
        cmds:
          - go run cmd/migrator/main.go --storage-path="./storage/sso.db" --migrations-path="./tests/migrations" --migrations-table="migrations_test"
    test:func:
        desc: "Run functional tests"
        cmds:
          - go test -v ./tests/