version: "3"

tasks:
    generate:
        desc: "Generate protobuf files"
        cmds:
          - protoc -I proto proto/auth.proto --go_out=./internal/proto/auth --go_opt=paths=source_relative --go_grpc_out=./internal/proto/auth --go_grpc_opt=paths=source_relative
    run:local:
        desc: "Run the server in local environment"
        cmds:
          - go run cmd/sso/main.go --config="./config/local.yml"